<?php
/**
 * SearchWP Engine: default
 * Maximum Results: 3
 */

/**
 * This is the default SearchWP Related results template. If you would like to
 * customize this template, DO NOT EDIT THIS FILE. Instead, create a folder
 * named 'searchwp-related' in your active theme, and copy this file inside.
 *
 * You may create multiple results templates based on the post being viewed,
 * simply append the post type name to the file name like so:
 *
 *      ~/your-theme-folder/searchwp-related/related-page.php
 *
 * That template file will be used whenever you view a Page on your site, while
 * the default (related.php) template would be used for everything else.
 *
 * You may customize the SearchWP engine used to find results by editing
 * the "SearchWP Engine" name at the top of this file.
 *
 * You may customize the number of related entries returned by that engine
 * by editing the "Maximum Results" at the top of this file.
 */

// DO NOT remove global $post; unless you're being intentional
global $post;

/**
 * $searchwp_related is an array of posts, defined within the SearchWP Related plugin
 */
if ( isset( $searchwp_related ) && ! empty( $searchwp_related ) ) : ?>

<div class="searchwp-related">
	<h4>Choose Related Content (optional)</h4>
	<ol>
		<?php foreach ( $searchwp_related as $post ) : setup_postdata( $post ); ?>
		<li>
			<a href="<?= esc_url( get_permalink() ) ?>" title="Set <?php the_title_attribute() ?> as Related Content">
				<?php the_post_thumbnail() ?>
				<span><?php the_title() ?></span>
			</a>
		</li>
		<?php endforeach; wp_reset_postdata(); ?>
	</ol>
</div>

<?php endif ?>