name: SFTP Deployment
on:
  push:
    branches:
      - main  # Adjust the branch name as needed!
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Identify changed files
        id: files
        run: |
          echo "::set-output name=list::$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})"
      
      - name: Deploy to SFTP Server
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SFTP_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          eval `ssh-agent -s`
          ssh-add ~/.ssh/id_rsa
          sftp -P 64779 bgrmjctda@35.196.247.55 << EOF
            cd /www/bgrmjctda_167/public/
            $(for file in ${{ steps.files.outputs.list }}; do echo put $file; done)
            bye
          EOF
        env:
          SFTP_PRIVATE_KEY: ${{ secrets.SFTP_PRIVATE_KEY }}