name: SFTP Deployment
on:
  push:
    branches:
      - main  # Adjust the branch name as needed!
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Setup SSH Keys and known_hosts
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SFTP_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 35.196.247.55 >> ~/.ssh/known_hosts

      - name: Rsync files to SFTP Server
        run: |
          rsync -avz --delete -e "ssh -p 64779" ./wp-content/themes/jc-network bgrmjctda@35.196.247.55:/www/bgrmjctda_167/public/wp-content/themes/jc-network
        env:
          SFTP_PRIVATE_KEY: ${{ secrets.SFTP_PRIVATE_KEY }}
