name: SFTP Deployment
on:
  push:
    branches:
      - main  # Adjust the branch name as needed!
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      
      - name: ssh-checking
        run: ssh -i ${{ secrets.SSH_PRIVATE_KEY }} bgrmjctda@35.196.247.55 -p 64779 

      - name: SFTP Upload
        run: scp -P 64779 -r ./wp-content/themes/*  bgrmjctda@35.196.247.55:/www/bgrmjctda_167/public/wp-content/themes/
