name: SFTP Deployment
on:
  push:
    branches:
      - main  # Adjust the branch name as needed!
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Identify changed files
        id: files
        run: |
          echo "list<<EOF" >> $GITHUB_ENV
          git diff --name-only ${{ github.event.before }} ${{ github.sha }} >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
      
      - name: Deploy to SFTP Server
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SFTP_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          eval `ssh-agent -s`
          ssh-add ~/.ssh/id_rsa
          sftp -o StrictHostKeyChecking=no -P 64779 bgrmjctda@35.196.247.55 << EOF
            cd /www/bgrmjctda_167/public/
            $(while IFS= read -r file; do
           if [ -f "$file" ]; then # Ensure it's a file, not a directory
                # Extract directory path from file path and create it on the server
                echo "mkdir -p $(dirname "$file")"
                echo "put $file $(dirname "$file")/"
              fi
            done <<< "${{ env.list }}")
            bye
          EOF
        env:
          SFTP_PRIVATE_KEY: ${{ secrets.SFTP_PRIVATE_KEY }}