name: SFTP Deployment
on:
  push:
    branches:
      - main  # Adjust the branch name as needed!
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: List all files before the push
        id: files_before
        run: |
          git fetch --depth=1 origin ${{ github.event.before }}
          echo "files_before<<EOF" >> $GITHUB_ENV
          git ls-tree -r ${{ github.event.before }} --name-only >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: List all files after the push
        id: files_after
        run: |
          echo "files_after<<EOF" >> $GITHUB_ENV
          git ls-tree -r ${{ github.sha }} --name-only >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Deploy changes and handle deletions
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SFTP_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          eval $(ssh-agent -s)
          ssh-add ~/.ssh/id_rsa
          
          # Upload and directory creation
          while IFS= read -r file; do
            if [ -f "$file" ]; then
              DIR=$(dirname "$file")
              ssh -o StrictHostKeyChecking=no -p 64779 bgrmjctda@35.196.247.55 "mkdir -p /www/bgrmjctda_167/public/$DIR"
              sftp -o StrictHostKeyChecking=no -P 64779 bgrmjctda@35.196.247.55 <<< $"put $file /www/bgrmjctda_167/public/$DIR/"
            fi
          done <<< "${{ env.files_after }}"

          # Handling deletions
          comm -23 <(echo "${{ env.files_before }}" | sort) <(echo "${{ env.files_after }}" | sort) | while IFS= read -r deleted_file; do
            ssh -o StrictHostKeyChecking=no -p 64779 bgrmjctda@35.196.247.55 "rm -f /www/bgrmjctda_167/public/$deleted_file"
          done
        env:
          SFTP_PRIVATE_KEY: ${{ secrets.SFTP_PRIVATE_KEY }}